language: java
notifications:
  hipchat:
    rooms:
      secure: Sm2Oq5HqiMhDRO2bPdRv6T1wwNjxcNDd2DRIKE4XqILjR4aqc6IlB+Jq3AvjCVyoJRT0o/DVJS6EiY9wDFHr1JhOUG3V/6q+QpXtD4A5bqwL0d29bfsxj67y6Vt68+9tdnozJCG4bAT19aCVpDBpaTvmTeg6yym9eROJpA6hyitwZgwqQf1uXENoH/MO2Ut9HFqtgM3W1rAqYpew+GMuGSVngyfVGTTI8Nf0ByqooHgDZc3EIhKJvDj1tbmTWoMQprvN7A7X0rLTYs1KX47zSXcNFgMI9bYgRpqeXbI7iS3iJzF4gkS9L+Q9/+r7ujkpcNj1QHebFzkbKjdhk+l9Nz8CPefNQ0uGDBCkaMTuroVhnTkMl397GcrQ5OcEjZmM1CqQjiVqn5pvQLbgQ//DuX6Lug1RpD2eCw1/IVf4jBPDaIKd4WvL1cMmokQLnRXopbYODsQAvA5ZH39ki2IgGsVDxFixrigPU7KSb86116zB4UEvM8p8zJHTskCbXL5eIU0pG8LexP/rwv14xm81pIngYvWpsKrFC1k7d3z2EO0cH2Kvh7D0S6YopM2HmqeqjMhHqT748nognusg+0yzSB9u0vgysVFNGxNCNErgr1XzYQAqO97pK4rY+yj25PmT+b/iszq95TJEWdS8/RLG/JLXMEkMtyIJ1o5HGSQO8bA=
deploy:
  provider: releases
  api_key:
    secure: xXQTnU1tZvK4pzD936ggd61FP7m8Gpq7393wv8gQ5qzyGUvQCRrkUFC/0fUAOnNvZm0h2HZ4y7tvJIqiGqPx8q+p3sZR3cZ5OOUTiL5BxMntj0BowS7DhpFmcRDggQy7/frvzRoFFiRks2fFUiAh9reANcHNeWlPvDkvpNZyajOpnpvvwd7PWevCYKA1e5yg3Bv3qup2xW4601qfw9SXtIRW92Yi71Hy3aWlo/F+aluACS5vIwCJueRV749UDfhPUgduzleqKdWQ6ePD/eNFLtBCjIQP2r/4tshim0HiRuy63AUcNg7lZZX+gSIbYQLvKI99n5Pg29yfiMrgRcHeSgczuKE/Y8MaxY04mgVgKf5+imJn5WG2KhL56hjFlBujQcvtMziJ+bXEyqahIhQ5HN9ZZm26XSZin/s72xHPb/+ZX93VPWcbcXVOgXbp6CRrrk0YILRHgg9HnOhJQYggbGwGUvN4beOuQ5THfqouOksmui7kiBLh1XFXYPJwOWMXafoJ8fCUQM2Hh9BGViIXi274HMrZM81uurUuXnHtvLGHXa9cwed/AfAJuwkndhNfkLqMAK+eEs0EUD8f47+ZmE9UwhH9XI3vuvNAwX5nMp5GLULpRrDGv6X+7CIdOc2T8TF7eX28np39Ph9bK/59mY4GZLKxr0nasNUJ203d5ZU=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-folder-plugin
